# Generated by Django 4.1.13 on 2026-08-14 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10, unique=True)),
                ('tipo', models.CharField(choices=[('local', 'Local'), ('boleteria', 'Boletería'), ('pescaderia', 'Pescadería'), ('lote6', 'Lote 6'), ('kiosco', 'Kiosco')], max_length=20)),
                ('ocupado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('caja', 'Caja'), ('tesoreria', 'Tesorería'), ('administrador', 'Administrador')], default='caja', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('mes', models.CharField(blank=True, max_length=20)),
                ('empresario', models.CharField(blank=True, max_length=150)),
                ('rut', models.CharField(blank=True, max_length=15)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('folio', models.CharField(max_length=30, unique=True)),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='core.local')),
            ],
        ),
    ]
