# Generated by Django 4.1.13 on 2026-08-24 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_loginlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local',
            name='tipo',
            field=models.CharField(choices=[('local', 'Local'), ('boleteria', 'Boletería'), ('pescaderia', 'Pescadería'), ('lote6', 'Lote 6'), ('kiosco', 'Kiosco'), ('centro_comercial', 'Centro Comercial')], max_length=20),
        ),
    ]
