# Generated by Django 4.1.13 on 2026-08-24 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_local_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historial',
            name='accion',
            field=models.CharField(choices=[('crear', 'Crear pago'), ('abonar', 'Abonar'), ('generar', 'Generar deuda')], max_length=20),
        ),
    ]
