# Generated by Django 4.1.13 on 2026-09-02 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_historial_accion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historial',
            name='accion',
            field=models.CharField(choices=[('crear', 'Crear pago'), ('abonar', 'Abonar'), ('editar', 'Editar pago'), ('eliminar', 'Eliminar pago'), ('generar', 'Generar deuda')], max_length=20),
        ),
    ]
