# Generated by Django 4.1.13 on 2026-09-03 17:57

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_historial_accion'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('dia', models.CharField(blank=True, max_length=15)),
                ('valor', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_diarios', to='core.pago')),
            ],
            options={
                'ordering': ['fecha'],
            },
        ),
    ]
