# Generated by Django 4.1.13 on 2026-09-03 19:00

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_pagodiario'),
    ]

    operations = [
        migrations.AddField(
            model_name='local',
            name='cantidad_utm',
            field=models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=10),
        ),
    ]
