# Generated by Django 4.1.13 on 2026-09-03 19:17

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_local_cantidad_utm'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValorUTM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('valor', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('asignado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('anio', 'mes')},
            },
        ),
    ]
