# Generated by Django 4.1.13 on 2026-09-16 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_valorutm'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagodiario',
            name='folio',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
