# Generated by Django 4.1.13 on 2026-09-23 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_pagodiario_folio'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='correo',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='pago',
            name='domicilio',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='pago',
            name='fono',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='pago',
            name='periodo',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='pago',
            name='tipo_deuda',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
